
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 20;
  public static final int RBRACK = 11;
  public static final int GEQ = 14;
  public static final int OVER = 21;
  public static final int LT = 16;
  public static final int ELSE = 3;
  public static final int PLUS = 18;
  public static final int INT = 22;
  public static final int RBRACE = 9;
  public static final int RPAREN = 7;
  public static final int SEMI = 26;
  public static final int WHILE = 4;
  public static final int LBRACK = 10;
  public static final int RETURN = 5;
  public static final int ERROR = 27;
  public static final int IF = 2;
  public static final int GT = 17;
  public static final int LPAREN = 6;
  public static final int LBRACE = 8;
  public static final int ID = 24;
  public static final int NUM = 25;
  public static final int COMMA = 28;
  public static final int EOF = 0;
  public static final int MINUS = 19;
  public static final int error = 1;
  public static final int ASSIGN = 29;
  public static final int EQ = 15;
  public static final int LEQ = 13;
  public static final int VOID = 23;
  public static final int NEQ = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "NEQ",
  "LEQ",
  "GEQ",
  "EQ",
  "LT",
  "GT",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "INT",
  "VOID",
  "ID",
  "NUM",
  "SEMI",
  "ERROR",
  "COMMA",
  "ASSIGN"
  };
}

